#Welcome to Jekyll!

#Site settings
title: Pare and Flourish
description: A personal development blog about living life according to the needs of oneâ€™s inner being, written by those still trying to find their inner being.
owner: Pare and Flourish #Company name.
first_published: 2016 
email: your-email@domain.com
baseurl: ""
url: ""
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>

Authors:
  Katie:
    Description:
  Skylar:
    Description

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Navigation
defaults:
  - scope:
      path: _posts
      type: blog
    values:
      layout: pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: pages
